import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FiZap, FiCalendar, FiTrendingUp, FiArrowRight, FiClock, FiTarget } from 'react-icons/fi';
import Button from '../components/ui/Button';

const features = [
  {
    icon: <FiZap size={28} />,
    title: 'AI-Powered Plans',
    description: 'Get personalized day-by-day study schedules generated by Mistral AI in seconds.',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
  },
  {
    icon: <FiCalendar size={28} />,
    title: 'Smart Scheduling',
    description: 'Automatic revision slots, break times, and priority-based topic distribution.',
    gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
  },
  {
    icon: <FiTrendingUp size={28} />,
    title: 'Progress Tracking',
    description: 'Track your daily tasks, monitor progress with charts, and maintain study streaks.',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
  },
  {
    icon: <FiClock size={28} />,
    title: 'Time Management',
    description: 'Set daily study hours and let AI optimize your time across all subjects.',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
  },
  {
    icon: <FiTarget size={28} />,
    title: 'Goal Oriented',
    description: 'Set clear deadlines and track your progress towards completing your goals.',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
  },
  {
    icon: <FiZap size={28} />,
    title: 'Export & Share',
    description: 'Download your study plans as PDF files or share them with study partners.',
    gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
  },
];

const containerVariants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.1,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

export default function Home() {
  return (
    <div style={{ minHeight: '100vh', overflow: 'hidden' }}>
      {/* Hero Section */}
      <section
        style={{
          position: 'relative',
          minHeight: '85vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '80px 24px',
          overflow: 'hidden',
        }}
        className="gradient-bg"
      >
        {/* Animated orbs */}
        <div className="orb orb-1" />
        <div className="orb orb-2" />
        <div className="orb orb-3" />

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          style={{
            textAlign: 'center',
            maxWidth: '800px',
            position: 'relative',
            zIndex: 10,
          }}
        >
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2 }}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '8px',
              padding: '6px 16px',
              borderRadius: '50px',
              background: 'rgba(99, 102, 241, 0.15)',
              border: '1px solid rgba(99, 102, 241, 0.3)',
              fontSize: '13px',
              fontWeight: 600,
              color: 'var(--primary-light)',
              marginBottom: '24px',
            }}
          >
            <FiZap size={14} />
            Powered by Mistral AI
          </motion.div>

          {/* Heading */}
          <h1
            style={{
              fontSize: 'clamp(36px, 6vw, 72px)',
              fontWeight: 900,
              lineHeight: 1.1,
              letterSpacing: '-0.03em',
              marginBottom: '24px',
            }}
          >
            <span className="gradient-text">AI-Powered</span>
            <br />
            <span style={{ color: 'var(--text-primary)' }}>Study Planner</span>
          </h1>

          {/* Subheading */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4 }}
            style={{
              fontSize: 'clamp(16px, 2vw, 20px)',
              color: 'var(--text-secondary)',
              maxWidth: '560px',
              margin: '0 auto 40px',
              lineHeight: 1.7,
            }}
          >
            Generate personalized study plans in 30 seconds. Smart scheduling,
            revision slots, and progress tracking — all powered by AI.
          </motion.p>

          {/* CTA Buttons */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            style={{ display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap' }}
          >
            <Link to="/dashboard/new" style={{ textDecoration: 'none' }}>
              <Button size="lg">
                Create Study Plan
                <FiArrowRight size={18} />
              </Button>
            </Link>
            <Link to="/dashboard" style={{ textDecoration: 'none' }}>
              <Button variant="secondary" size="lg">
                View Dashboard
              </Button>
            </Link>
          </motion.div>

          {/* Stats */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1 }}
            style={{
              display: 'flex',
              gap: '40px',
              justifyContent: 'center',
              marginTop: '60px',
              flexWrap: 'wrap',
            }}
          >
            {[
              { value: 'AI', label: 'Powered Generation' },
              { value: '30s', label: 'Average Time' },
              { value: '∞', label: 'Custom Plans' },
            ].map((stat) => (
              <div key={stat.label} style={{ textAlign: 'center' }}>
                <div
                  className="gradient-text"
                  style={{ fontSize: '32px', fontWeight: 800, lineHeight: 1 }}
                >
                  {stat.value}
                </div>
                <div
                  style={{
                    fontSize: '13px',
                    color: 'var(--text-muted)',
                    marginTop: '4px',
                    fontWeight: 500,
                  }}
                >
                  {stat.label}
                </div>
              </div>
            ))}
          </motion.div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section
        style={{
          padding: '100px 24px',
          maxWidth: '1200px',
          margin: '0 auto',
        }}
      >
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          style={{ textAlign: 'center', marginBottom: '60px' }}
        >
          <h2
            style={{
              fontSize: 'clamp(28px, 4vw, 42px)',
              fontWeight: 800,
              letterSpacing: '-0.02em',
              marginBottom: '16px',
            }}
          >
            Everything you need to{' '}
            <span className="gradient-text">study smarter</span>
          </h2>
          <p
            style={{
              fontSize: '17px',
              color: 'var(--text-secondary)',
              maxWidth: '520px',
              margin: '0 auto',
            }}
          >
            Our AI analyzes your goals, deadlines, and preferences to create the perfect study plan.
          </p>
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: '24px',
          }}
        >
          {features.map((feature, i) => (
            <motion.div
              key={i}
              variants={itemVariants}
              className="glass-card"
              style={{
                padding: '32px',
                cursor: 'default',
              }}
            >
              <div
                style={{
                  width: '52px',
                  height: '52px',
                  borderRadius: '14px',
                  background: feature.gradient,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'white',
                  marginBottom: '20px',
                }}
              >
                {feature.icon}
              </div>
              <h3
                style={{
                  fontSize: '18px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'var(--text-primary)',
                }}
              >
                {feature.title}
              </h3>
              <p style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* CTA Section */}
      <section
        style={{
          padding: '80px 24px',
          textAlign: 'center',
        }}
      >
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          style={{
            maxWidth: '640px',
            margin: '0 auto',
            padding: '60px 40px',
            borderRadius: '24px',
            background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(6, 182, 212, 0.1))',
            border: '1px solid rgba(99, 102, 241, 0.2)',
          }}
        >
          <h2
            style={{
              fontSize: '28px',
              fontWeight: 800,
              marginBottom: '16px',
              letterSpacing: '-0.02em',
            }}
          >
            Ready to study smarter?
          </h2>
          <p
            style={{
              color: 'var(--text-secondary)',
              marginBottom: '32px',
              fontSize: '15px',
            }}
          >
            Create your first AI-powered study plan in under a minute.
          </p>
          <Link to="/dashboard/new" style={{ textDecoration: 'none' }}>
            <Button size="lg">
              Get Started Free <FiArrowRight />
            </Button>
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer
        style={{
          padding: '32px 24px',
          textAlign: 'center',
          borderTop: '1px solid var(--border)',
        }}
      >
        <p style={{ fontSize: '13px', color: 'var(--text-muted)' }}>
          © {new Date().getFullYear()} StudyFlow AI. Built with React, Tailwind CSS & Hugging Face.
        </p>
      </footer>
    </div>
  );
}
